### PR TITLE
Add missing XML comments to Extensions

### PR DESCRIPTION
**Pull request by hey-mikey**
- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [ ] Manually tested
- [ ] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [x] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

Fix for #37

### CODE REVIEW

**Comment by brandongregoryscott** [comment]
@hey-mikey Thanks for filling in these XML comment stubs. Would you be able to fix up the merge conflict?

**Review by brandongregoryscott — CHANGES_REQUESTED** [review]
@hey-mikey Thanks for filling in these XML comment stubs. Would you be able to fix up the merge conflict?

**Comment by hey-mikey** [comment]
> @hey-mikey Thanks for filling in these XML comment stubs. Would you be able to fix up the merge conflict?

Sure thing, sorry about that!

**Review by brandongregoryscott — APPROVED** [review]

**Comment by brandongregoryscott** [comment]
> > @hey-mikey Thanks for filling in these XML comment stubs. Would you be able to fix up the merge conflict?
> 
> Sure thing, sorry about that!

No worries! A lot of comments have been changing with all of the hacktoberfest PRs, and I think this one sat for a few days w/o being reviewed. Thanks again for the contribution!

**Pull request merged**
